export default function Head() {
  return (
    <>
      <title>Mayur Lalwani</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <script async src="https://eu.umami.is/script.js" data-website-id="0bd010de-069e-437a-8c2a-e739e0eb5583"></script>
      <link
        rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>👋</text></svg>"
      />
    </>
  );
}
